import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useCollection } from "react-firebase-hooks/firestore";
import {
  collection,
  getDocs,
  query,
  CollectionReference,
  DocumentData,
  Timestamp,
} from "firebase/firestore";
import { db, postToJSON } from "@/lib/firebase";
import { useEffect, useState } from "react";

interface WishInterface {
  createdAt: Timestamp;
  createdBy: string;
  description: string;
  links: string[];
  title: string[];
}

interface Message {
  messageText: string;
  sentAt: Timestamp;
  sentBy: string;
}

export default function Home() {
  const q = query(
    collection(db, "wishes") as CollectionReference<WishInterface>
  );
  const [queryCollection] = useCollection(q);
  const wishes = queryCollection?.docs.map((doc) => postToJSON(doc));
  const [clickedWish, setClickedWish] = useState<string | null>(null);

  const [discussion, setDiscussion] = useState<Message[]>([]);

  useEffect(() => {
    if (queryCollection && clickedWish) {
      const discussionQuery = query(
        collection(
          db,
          "wishes",
          clickedWish,
          "publicChat"
        ) as CollectionReference<Message>
      );
      getDocs(discussionQuery).then((res) =>
        setDiscussion(res.docs.map((doc) => doc.data()))
      );
    }
  }, [queryCollection, clickedWish]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {wishes &&
          wishes.map((wish, index) => (
            <div onClick={() => setClickedWish(wish.id)} key={index}>
              {wish.title}
            </div>
          ))}

        <ul>
          {discussion.map((msg, index) => (
            <li key={index}>{msg.messageText}</li>
          ))}
        </ul>
      </main>
    </>
  );
}
